version: "3"

services:
  pruebabam-img-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: pruebabam-img-dev
    container_name: pruebabam-cont-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"